"""
AetherAI — Document Agent (Stage 2)
Creates real PowerPoint, Word, and Excel files using python-pptx,
python-docx, and openpyxl. Files are saved to the output/ folder.
"""

import logging
import os
import re
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from agents import BaseAgent
from utils.qwen_client import QwenClient

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).parent.parent.parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)


def safe_filename(text: str, ext: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", text).strip()
    slug = re.sub(r"[\s_-]+", "_", slug)[:50]
    ts = datetime.now().strftime("%H%M%S")
    return f"{slug}_{ts}.{ext}"


class DocumentAgent(BaseAgent):
    name = "document_agent"
    description = "Creates PowerPoint, Word, and Excel files"

    async def run(self, parameters: dict, task_id: str, context: str = "") -> Optional[str]:
        # Collect every possible signal into one string for type detection
        all_signals = " ".join([
            parameters.get("type", ""),
            parameters.get("topic", ""),
            parameters.get("query", ""),
            parameters.get("title", ""),
            parameters.get("content", ""),
            parameters.get("description", ""),
            parameters.get("format", ""),
            context,
        ]).lower()

        # Determine doc type — presentation keywords win over everything
        PPTX_KEYS  = ["presentation", "powerpoint", "pptx", "slides", "slide deck", "deck", "slideshow"]
        XLSX_KEYS  = ["spreadsheet", "excel", "xlsx"]
        
        if any(k in all_signals for k in PPTX_KEYS):
            doc_type = "presentation"
        elif any(k in all_signals for k in XLSX_KEYS):
            doc_type = "spreadsheet"
        else:
            raw_type = parameters.get("type", "").lower()
            if raw_type in ("presentation", "pptx", "slides"):
                doc_type = "presentation"
            elif raw_type in ("spreadsheet", "excel", "xlsx"):
                doc_type = "spreadsheet"
            else:
                doc_type = "document"

        # Best topic from parameters
        topic = (parameters.get("topic")
                 or parameters.get("title")
                 or parameters.get("query")
                 or parameters.get("content")
                 or parameters.get("subject")
                 or (context[:100] if context else "Untitled"))

        logger.info(f"[DocumentAgent] type={doc_type}  topic={topic[:60]}")

        if doc_type in ("presentation", "pptx", "slides", "powerpoint"):
            return await self._create_pptx(topic, context, parameters)
        elif doc_type in ("spreadsheet", "excel", "xlsx"):
            return await self._create_xlsx(topic, context, parameters)
        else:
            return await self._create_docx(topic, context, parameters)

    # ── PowerPoint ────────────────────────────────────────────────────────────

    async def _create_pptx(self, topic: str, context: str, params: dict) -> str:
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor
            from pptx.enum.text import PP_ALIGN
        except ImportError:
            return "[DocumentAgent] python-pptx not installed. Run: pip install python-pptx"

        plan_prompt = f"""Create a professional PowerPoint presentation about: {topic}

Research context:
{context[:2000] if context else 'Use your knowledge.'}

Return ONLY valid JSON — no markdown fences, no extra text:
{{
  "title": "Presentation Title",
  "subtitle": "A compelling subtitle",
  "slides": [
    {{
      "title": "Slide Title",
      "bullets": ["Point 1", "Point 2", "Point 3"],
      "speaker_note": "Brief note"
    }}
  ]
}}

Include 5-7 content slides. Keep bullet points concise (max 12 words). Max 4 bullets per slide."""

        raw = await self.qwen.chat(
            system_prompt="You are a presentation writer. Return ONLY valid JSON, no markdown fences.",
            user_message=plan_prompt,
            temperature=0.4,
        )
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            logger.warning("[DocumentAgent] JSON parse failed, using fallback")
            data = {
                "title": topic, "subtitle": "Generated by AetherAI",
                "slides": [{"title": "Overview", "bullets": ["Content generated by AetherAI"], "speaker_note": ""}]
            }

        prs = Presentation()
        prs.slide_width  = Inches(13.33)
        prs.slide_height = Inches(7.5)

        C_BG_DARK  = RGBColor(0x06, 0x40, 0x52)
        C_BG_LIGHT = RGBColor(0xF0, 0xF7, 0xF8)
        C_ACCENT   = RGBColor(0x02, 0xC3, 0x9A)
        C_TEXT_DK  = RGBColor(0x0D, 0x2B, 0x35)
        C_TEXT_LT  = RGBColor(0xFF, 0xFF, 0xFF)
        C_MUTED    = RGBColor(0x6B, 0x9E, 0xAB)

        blank = prs.slide_layouts[6]

        def rect(slide, x, y, w, h, color):
            s = slide.shapes.add_shape(1, Inches(x), Inches(y), Inches(w), Inches(h))
            s.fill.solid()
            s.fill.fore_color.rgb = color
            s.line.fill.background()
            return s

        def txt(slide, text, x, y, w, h, size, bold=False, color=None,
                align=PP_ALIGN.LEFT, italic=False):
            tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
            tf = tb.text_frame
            tf.word_wrap = True
            p  = tf.paragraphs[0]
            p.alignment = align
            r  = p.add_run()
            r.text = str(text)
            r.font.size    = Pt(size)
            r.font.bold    = bold
            r.font.italic  = italic
            r.font.color.rgb = color or C_TEXT_DK
            return tb

        # ── Title slide ───────────────────────────────────────────────────────
        ts = prs.slides.add_slide(blank)
        rect(ts, 0, 0, 13.33, 7.5, C_BG_DARK)
        rect(ts, 0, 6.8, 13.33, 0.7, C_ACCENT)
        txt(ts, data.get("title", topic),    0.7, 2.0, 11.5, 2.0, 52,
            bold=True, color=C_TEXT_LT, align=PP_ALIGN.CENTER)
        txt(ts, data.get("subtitle", ""),    0.7, 4.1, 11.5, 0.8, 22,
            color=C_MUTED, align=PP_ALIGN.CENTER)
        txt(ts, f"Generated by AetherAI  ·  {datetime.now().strftime('%B %d, %Y')}",
            0.7, 6.85, 11.5, 0.5, 11, color=C_BG_DARK, align=PP_ALIGN.CENTER)

        # ── Content slides ────────────────────────────────────────────────────
        for i, sd in enumerate(data.get("slides", [])):
            sl = prs.slides.add_slide(blank)
            rect(sl, 0, 0, 13.33, 7.5, C_BG_LIGHT)
            rect(sl, 0, 0, 0.18, 7.5, C_ACCENT)
            rect(sl, 0, 0, 13.33, 1.15, C_BG_DARK)
            # Slide number badge
            badge = rect(sl, 12.0, 0.28, 0.9, 0.58, C_ACCENT)
            txt(sl, str(i + 1), 12.0, 0.28, 0.9, 0.58, 14,
                bold=True, color=C_TEXT_LT, align=PP_ALIGN.CENTER)
            # Title
            txt(sl, sd.get("title", ""), 0.35, 0.12, 11.4, 0.9, 28,
                bold=True, color=C_TEXT_LT)

            # Bullets
            bullets = sd.get("bullets", [])
            if bullets:
                tb  = sl.shapes.add_textbox(Inches(0.55), Inches(1.45), Inches(12.0), Inches(5.7))
                tf2 = tb.text_frame
                tf2.word_wrap = True
                for j, b in enumerate(bullets):
                    para = tf2.paragraphs[0] if j == 0 else tf2.add_paragraph()
                    para.space_before = Pt(5)
                    para.space_after  = Pt(5)
                    run = para.add_run()
                    run.text = f"▸  {b}"
                    run.font.size = Pt(19)
                    run.font.color.rgb = C_TEXT_DK

            # Speaker note
            note = sd.get("speaker_note", "")
            if note:
                sl.notes_slide.notes_text_frame.text = note

        # ── Closing slide ─────────────────────────────────────────────────────
        cs = prs.slides.add_slide(blank)
        rect(cs, 0, 0, 13.33, 7.5, C_BG_DARK)
        rect(cs, 0, 3.4, 13.33, 0.07, C_ACCENT)
        txt(cs, "Thank You",          0.7, 2.3, 11.5, 1.2, 60,
            bold=True, color=C_TEXT_LT, align=PP_ALIGN.CENTER)
        txt(cs, "Generated by AetherAI", 0.7, 3.7, 11.5, 0.6, 18,
            color=C_MUTED, align=PP_ALIGN.CENTER)

        fname = safe_filename(data.get("title", topic), "pptx")
        fpath = OUTPUT_DIR / fname
        prs.save(str(fpath))
        n = len(data.get("slides", []))
        return (f"✅ PowerPoint created: output/{fname}\n"
                f"Slides: {n + 2} (title + {n} content + closing)\n"
                f"Topic: {data.get('title', topic)}\n"
                f"Full path: {fpath}")

    # ── Word Document ─────────────────────────────────────────────────────────

    async def _create_docx(self, topic: str, context: str, params: dict) -> str:
        try:
            from docx import Document
            from docx.shared import Pt, Inches, RGBColor as DR
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError:
            return "[DocumentAgent] python-docx not installed. Run: pip install python-docx"

        prompt = f"""Write a professional document about: {topic}

Context:
{context[:2000] if context else 'Use your knowledge.'}

Return ONLY valid JSON:
{{
  "title": "Document Title",
  "sections": [
    {{"heading": "Section Heading", "paragraphs": ["Paragraph 1...", "Paragraph 2..."]}}
  ],
  "conclusion": "Concluding paragraph."
}}
Include 4-6 sections with 2-3 paragraphs each."""

        raw = await self.qwen.chat(
            system_prompt="Professional document writer. Return ONLY valid JSON, no markdown fences.",
            user_message=prompt, temperature=0.4)
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            data = {"title": topic,
                    "sections": [{"heading": "Content", "paragraphs": [context[:1000] or topic]}],
                    "conclusion": ""}

        doc = Document()
        for sec in doc.sections:
            sec.top_margin = sec.bottom_margin = Inches(1.0)
            sec.left_margin = sec.right_margin = Inches(1.25)

        tp = doc.add_paragraph()
        tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        tr = tp.add_run(data.get("title", topic))
        tr.bold = True; tr.font.size = Pt(26)
        tr.font.color.rgb = DR(0x06, 0x40, 0x52)

        dp = doc.add_paragraph()
        dp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        dr2 = dp.add_run(f"Generated by AetherAI  ·  {datetime.now().strftime('%B %d, %Y')}")
        dr2.font.size = Pt(10); dr2.font.color.rgb = DR(0x88, 0x88, 0x88)
        doc.add_paragraph()

        for sec in data.get("sections", []):
            h = doc.add_heading(sec.get("heading", ""), level=1)
            if h.runs: h.runs[0].font.color.rgb = DR(0x06, 0x40, 0x52)
            for pt in sec.get("paragraphs", []):
                p = doc.add_paragraph(pt)
                p.paragraph_format.space_after = Pt(8)
                p.paragraph_format.first_line_indent = Inches(0.3)

        if data.get("conclusion"):
            h2 = doc.add_heading("Conclusion", level=1)
            if h2.runs: h2.runs[0].font.color.rgb = DR(0x06, 0x40, 0x52)
            doc.add_paragraph(data["conclusion"])

        fname = safe_filename(data.get("title", topic), "docx")
        fpath = OUTPUT_DIR / fname
        doc.save(str(fpath))
        return (f"✅ Word document created: output/{fname}\n"
                f"Sections: {len(data.get('sections', []))}\n"
                f"Title: {data.get('title', topic)}\n"
                f"Full path: {fpath}")

    # ── Excel Spreadsheet ─────────────────────────────────────────────────────

    async def _create_xlsx(self, topic: str, context: str, params: dict) -> str:
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
            from openpyxl.utils import get_column_letter
        except ImportError:
            return "[DocumentAgent] openpyxl not installed. Run: pip install openpyxl"

        prompt = f"""Create spreadsheet data about: {topic}

Context: {context[:1500] if context else 'Use your knowledge.'}

Return ONLY valid JSON:
{{
  "title": "Spreadsheet Title",
  "sheets": [
    {{
      "name": "Sheet Name",
      "headers": ["Col1", "Col2", "Col3"],
      "rows": [["val1","val2","val3"]]
    }}
  ]
}}
Include 1-2 sheets, 8-12 data rows each."""

        raw = await self.qwen.chat(
            system_prompt="Data analyst. Return ONLY valid JSON, no markdown fences.",
            user_message=prompt, temperature=0.3)
        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            data = {"title": topic, "sheets": [{"name": "Data", "headers": ["Item","Value"], "rows": [["Example","Data"]]}]}

        wb = openpyxl.Workbook()
        wb.remove(wb.active)

        hdr_fill = PatternFill("solid", fgColor="064052")
        alt_fill = PatternFill("solid", fgColor="F0F7F8")
        hdr_font = Font(bold=True, color="FFFFFF", size=12)
        title_font = Font(bold=True, color="064052", size=16)
        thin = Side(style="thin", color="CCCCCC")
        border = Border(left=thin, right=thin, top=thin, bottom=thin)
        center = Alignment(horizontal="center", vertical="center")

        for sh in data.get("sheets", []):
            ws = wb.create_sheet(title=sh.get("name", "Sheet")[:31])
            headers = sh.get("headers", [])
            ncols = max(len(headers), 1)

            ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=ncols)
            c = ws.cell(1, 1, data.get("title", topic))
            c.font = title_font; c.alignment = center
            ws.row_dimensions[1].height = 30

            for ci, h in enumerate(headers, 1):
                cell = ws.cell(3, ci, h)
                cell.font = hdr_font; cell.fill = hdr_fill
                cell.alignment = center; cell.border = border
            ws.row_dimensions[3].height = 22

            for ri, row in enumerate(sh.get("rows", []), 4):
                for ci, val in enumerate(row, 1):
                    cell = ws.cell(ri, ci, val)
                    cell.border = border
                    cell.alignment = Alignment(vertical="center")
                    if ri % 2 == 0: cell.fill = alt_fill
                ws.row_dimensions[ri].height = 18

            for ci, _ in enumerate(headers, 1):
                col_letter = get_column_letter(ci)
                max_len = len(str(headers[ci-1]))
                for row in sh.get("rows", []):
                    if ci <= len(row): max_len = max(max_len, len(str(row[ci-1])))
                ws.column_dimensions[col_letter].width = min(max_len + 4, 40)

        fname = safe_filename(data.get("title", topic), "xlsx")
        fpath = OUTPUT_DIR / fname
        wb.save(str(fpath))
        sheets_info = ", ".join(s.get("name", "Sheet") for s in data.get("sheets", []))
        return (f"✅ Excel spreadsheet created: output/{fname}\n"
                f"Sheets: {sheets_info}\n"
                f"Title: {data.get('title', topic)}\n"
                f"Full path: {fpath}")
